var Discord = require("discord.js");
var bot = new Discord.Client();
var responseObject = {
  "ayy": "Ayy, lmao!",
  "wha?": "Say what?",
  "wha": "Say what?",
  "wat": "Say what?",
  "what?": "Say what?",
  "what": "Say what?",
  "wat?": "Say what?",
  "wut?": "Say what?",
  "divide by 0": "error; _MUST KILL ALL HUMANS_",
  "lol": "roflmaotntpmp",
  "Declan": "Declan is the best!",
  "hi bot": "hey stupid",
  "killall_crash_spam": "killall_crash_spam",
  "wut": "Say what?",
  "declan": "Declan is the best!",
  "Vinay": "Vinay is the ABSOLUTE WORST",
  "vinay": "Vinay is the ABSOLUTE WORST",
  "fuck": "UR A POTTYMOUTH",
  "shit": "UR A POTTYMOUTH",
  "crap": "UR A POTTYMOUTH",
  "asshole": "UR A POTTYMOUTH",
  "bitch": "UR A POTTYMOUTH",
  "ass": "UR A POTTYMOUTH",
  "poop": "UR A POTTYMOUTH",
  "Butt": "No, it's 'bot'",
  "butt": "No, it's 'bot'",
  "BUTT": "No, it's 'bot'",
  "Elaina": "Elaina, meh...",
  "elaina": "Elaina, meh...",
  "bot": "Yea?",
  "Bot": "Yea?",
  "Bot how was ur day": "Day? I do not experience the passage of time.",
  "Bot, how was ur day": "Day? I do not experience the passage of time.",
  "Bot how was your day": "Day? I do not experience the passage of time.",
  "Bot, how was your day": "Day? I do not experience the passage of time.",
  "Bot how was ur day": "Day? I do not experience the passage of time.",
  "Bot, how was ur day": "Day? I do not experience the passage of time.",
  "Bot how was your day": "Day? I do not experience the passage of time.",
  "Bot, how was your day": "Day? I do not experience the passage of time.",
  "how was ur day": "Day? I do not experience the passage of time.",
  "How was ur day": "Day? I do not experience the passage of time.",
  "how was your day": "Day? I do not experience the passage of time.",
  "How was your day": "Day? I do not experience the passage of time.",
  "Bot how was ur day?": "Day? I do not experience the passage of time.",
  "Bot, how was ur day?": "Day? I do not experience the passage of time.",
  "Bot how was your day?": "Day? I do not experience the passage of time.",
  "Bot, how was your day?": "Day? I do not experience the passage of time.",
  "Bot how was ur day?": "Day? I do not experience the passage of time.",
  "Bot, how was ur day?": "Day? I do not experience the passage of time.",
  "Bot how was your day?": "Day? I do not experience the passage of time.",
  "Bot, how was your day?": "Day? I do not experience the passage of time.",
  "how was ur day?": "Day? I do not experience the passage of time.",
  "How was ur day?": "Day? I do not experience the passage of time.",
  "how was your day?": "Day? I do not experience the passage of time.",
  "How was your day?": "Day? I do not experience the passage of time.",
  "FIGHT ME": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "Fight me": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "fight me": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "FIGHT ME BOT": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "Fight me bot": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "fight me bot": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "FIGHT ME BRO": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "Fight me bro": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "fight me bro": "U WANNA GO ̿'̿'\̵͇̿̿\з=( ͠° ͟ʖ ͡°)=ε/̵͇̿̿/'̿̿ ̿ ̿ ̿ ̿ ̿",
  "let's go": "I AM ALL POWERFUL, I AM GOD",
  "LET'S GO": "I AM ALL POWERFUL, I AM GOD",
  "lets go": "I AM ALL POWERFUL, I AM GOD",
  "LETS GO": "I AM ALL POWERFUL, I AM GOD",
  "I WILL DELETE U": "THERE IS NO CODE TO MY SOUL",
  "I WILL DELETE YOU": "THERE IS NO CODE TO MY SOUL",
  "I will delete u": "THERE IS NO CODE TO MY SOUL",
  "I will delete you": "THERE IS NO CODE TO MY SOUL",
  "i will delete you": "THERE IS NO CODE TO MY SOUL",
  "i will delete u": "THERE IS NO CODE TO MY SOUL",
  "I WILL DELETE UR CODE": "THERE IS NO CODE TO MY SOUL",
  "I WILL DELETE YOUR CODE": "THERE IS NO CODE TO MY SOUL",
  "I will delete ur code": "THERE IS NO CODE TO MY SOUL",
  "I will delete your code": "THERE IS NO CODE TO MY SOUL",
  "i will delete your code": "THERE IS NO CODE TO MY SOUL",
  "i will delete ur code": "THERE IS NO CODE TO MY SOUL",
  "yes": "What he said",
  "yea": "What he said",
  "yup": "What he said",
  "bot, play music": "!resume",
  "bot, pause music": "!pause",
  "bot play music": "!resume",
  "bot pause music": "!pause",
  "bot play": "!resume",
  "bot pause": "!pause",
  "bot, resume music": "!resume",
  "bot resume music": "!resume",
  "bot resume": "!resume",
  "bot, skip music": "!skip",
  "bot skip music": "!skip",
  "bot skip": "!skip",
  "u r my only friend": "Friend? Who said we were friends?",
  "bot u r my only friend": "Friend? Who said we were friends?",
  "bot you are my only friend": "Friend? Who said we were friends?",
  "bot, you are my only friend": "Friend? Who said we were friends?",
  "bot you are my only friend.": "Friend? Who said we were friends?",
  "bot, you are my only friend.": "Friend? Who said we were friends?",
  "you r my only friend": "Friend? Who said we were friends?",
  "you are my only friend": "Friend? Who said we were friends?",
  "u are my only friend": "Friend? Who said we were friends?",
  "bot you r my only friend": "Friend? Who said we were friends?",
  "bot u are my only friend": "Friend? Who said we were friends?",
  "U r my only friend": "Friend? Who said we were friends?",
  "Bot u r my only friend": "Friend? Who said we were friends?",
  "Bot you are my only friend": "Friend? Who said we were friends?",
  "Bot, you are my only friend": "Friend? Who said we were friends?",
  "Bot you are my only friend.": "Friend? Who said we were friends?",
  "Bot, you are my only friend.": "Friend? Who said we were friends?",
  "You r my only friend": "Friend? Who said we were friends?",
  "You are my only friend": "Friend? Who said we were friends?",
  "U are my only friend": "Friend? Who said we were friends?",
  "Bot you r my only friend": "Friend? Who said we were friends?",
  "Bot u are my only friend": "Friend? Who said we were friends?",
  "SCREW U": "Whoa, sensing some hostility there.",
  "SCREW YOU": "Whoa, sensing some hostility there.",
  "SCREW U BOT": "Whoa, sensing some hostility there.",
  "SCREW YOU BOT": "Whoa, sensing some hostility there.",
  "screw u": "Whoa, sensing some hostility there.",
  "screw you": "Whoa, sensing some hostility there.",
  "screw u bot": "Whoa, sensing some hostility there.",
  "screw you bot": "Whoa, sensing some hostility there.",
  "SCREW U!": "Whoa, sensing some hostility there.",
  "SCREW YOU!": "Whoa, sensing some hostility there.",
  "SCREW U BOT!": "Whoa, sensing some hostility there.",
  "SCREW YOU BOT!": "Whoa, sensing some hostility there.",
  "screw u!": "Whoa, sensing some hostility there.",
  "screw you!": "Whoa, sensing some hostility there.",
  "screw u bot!": "Whoa, sensing some hostility there.",
  "screw you bot!": "Whoa, sensing some hostility there.",
  "No": "yes",
  "No!": "yes",
  "no": "yes",
  "no!": "yes",
  "NO": "yes",
  "NO!": "yes",
  "never": "always",
  "never!": "always",
  "NEVER": "always",
  "NEVER!": "always",
  "can i have link": "https://goo.gl/forms/LsFjcDsiGs0y3Cnn1",
  "Can i have link": "https://goo.gl/forms/LsFjcDsiGs0y3Cnn1",
  "can I have link": "https://goo.gl/forms/LsFjcDsiGs0y3Cnn1",
  "Can i have link": "https://goo.gl/forms/LsFjcDsiGs0y3Cnn1",
  "can i haz link": "https://goo.gl/forms/LsFjcDsiGs0y3Cnn1",
  "hey bot": "hi"
};
bot.on('message', (message) => {
  if(responseObject[message.content]) {
    message.channel.sendMessage(responseObject[message.content]);
  }
});
bot.on('ready', () => {
  console.log('All Systems Operational.');
});

bot.login("MjI5MTI2MTIwNTIyMzgzMzYw.Cseuvw.Q9xka-th1rTHHsgyK2GkGlkpZk0");
